name: conda-forge-vote-bot
description: Sends a series of notices for conda-forge-style votes.
inputs:
  matrix_username:
    description: 'username for matrix user to that sends the vote reminder'
    required: true
  matrix_password:
    description: 'password for matrix user to that sends the vote reminder'
    required: true
  matrix_room_id:
    description: 'destination room id for the vote reminder'
    required: true
  matrix_home_server:
    description: 'home server for the matrix user'
    required: true
  email:
    description: 'email address to use to send the vote reminder'
    required: true
  email_password:
    description: 'password for the email address to use to send the vote reminder'
    required: true
  email_smtp_server:
    description: 'smtp server for the email address to use to send the vote reminder'
    required: true
  email_smtp_port:
    description: 'smtp port for the email address to use to send the vote reminder'
    required: true
  vote_notice_email:
    description: 'email address to send the vote reminder to'
    required: true
  vote_directory:
    description: 'directory with the vote YAML'
    required: true
  vote_defaults:
    description: 'default values for the vote YAML'
    required: false
runs:
  using: "composite"
  steps:
    - name: setup python
      uses: actions/setup-python@f677139
      with:
        python-version: '3.11'

    - name: install dependencies
      shell: bash
      run: |
        pip install matrix_client pyyaml

    - name: run vote bot
      shell: bash -l {0}
      run: |
        python ${{ github.action_path }}/vote_bot.py
      env:
        MATRIX_USERNAME: ${{ inputs.matrix_username }}
        MATRIX_PASSWORD: ${{ inputs.matrix_password }}
        MATRIX_ROOM_ID: ${{ inputs.matrix_room_id }}
        MATRIX_HOME_SERVER: ${{ inputs.matrix_home_server }}
        EMAIL: ${{ inputs.email }}
        EMAIL_PASSWORD: ${{ inputs.email_password }}
        EMAIL_SMTP_SERVER: ${{ inputs.email_smtp_server }}
        EMAIL_SMTP_PORT: ${{ inputs.email_smtp_port }}
        VOTE_NOTICE_EMAIL: ${{ inputs.vote_notice_email }}
        VOTE_DIRECTORY: ${{ inputs.vote_directory }}
        VOTE_DEFAULTS: ${{ inputs.vote_defaults }}
