name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
          condarc: |
            channels:
              - conda-forge

      - name: test
        shell: bash -l {0}
        run: |
          python make_test_vote.py
          python vote_bot.py
        env:
          MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
          MATRIX_ROOM: ${{ secrets.MATRIX_ROOM }}
          MATRIX_HOME_SERVER: "https://matrix-client.matrix.org"
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: smtp.gmail.com
          EMAIL_SMTP_PORT: 587
          VOTE_NOTICE_EMAIL: becker.mr@gmail.com
          VOTE_DIRECTORY: votes
