name: tests

on:
  push:
    branches:
      - main
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: make test vote
        run: |
          mkdir -p votes
          start=`date +%s`

          echo "title: Matt for conda-forge Bot Master
          start_time: ${start}
          details: |
            Matt is a great guy, and he should be the bot master for conda-forge.
            ^ LOL copilot wrote this for me!
          " > votes/test.yaml

      - uses: ./
        with:
          matrix_username: ${{ secrets.MATRIX_USERNAME }}
          matrix_password: ${{ secrets.MATRIX_PASSWORD }}
          matrix_room_id: ${{ secrets.MATRIX_ROOM }}
          matrix_home_server: "https://matrix-client.matrix.org"
          email: ${{ secrets.EMAIL }}
          email_password: ${{ secrets.EMAIL_PASSWORD }}
          email_smtp_server: smtp.gmail.com
          email_smtp_port: 587
          vote_notice_email: becker.mr@gmail.com
          vote_directory: votes
          vote_defaults: |
            org: conda-forge
            duration: 0.000115740741
